name: Build CV PDF (Playwright + Fallback)

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch für Commit (leer = aktueller Branch)'
        required: false
        default: ''
      index_path:
        description: 'Pfad zur index.html (z.B. index.html oder resume/index.html)'
        required: false
        default: ''
  push:
    paths:
      - "index.html"
      - "resume/index.html"
      - ".github/workflows/build-cv-pdf.yml"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout (volle Historie)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.target_branch || github.ref_name }}

      - name: Repo-Layout (Debug)
        run: |
          echo "::group::tree"
          ls -la
          [ -d resume ] && (echo "--- resume/ ---" && ls -la resume)
          echo "::endgroup::"

      - name: Branch & index.html ermitteln
        id: setup
        run: |
          BRANCH="${{ github.event.inputs.target_branch || github.ref_name }}"
          if [ -n "${{ github.event.inputs.index_path }}" ]; then
            IDX="${{ github.event.inputs.index_path }}"
          elif [ -f "index.html" ]; then
            IDX="index.html"
          elif [ -f "resume/index.html" ]; then
            IDX="resume/index.html"
          else
            echo "❌ index.html nicht gefunden."
            exit 1
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "INDEX_PATH=$IDX" >> $GITHUB_ENV
          echo "→ Branch: $BRANCH"
          echo "→ index:  $IDX"

      - name: Node einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Playwright installieren (Chromium + Deps)
        run: |
          npm init -y
          npm i -D playwright@1.46.1
          npx playwright install --with-deps chromium

      - name: Export-Script (Playwright) schreiben
        run: |
          mkdir -p scripts assets
          cat > scripts/export-pdf.mjs <<'EOF'
          import { chromium } from "playwright";
          import { resolve, join } from "path";
          import fs from "fs";

          const indexPath = process.env.INDEX_PATH || "index.html";
          const fileUrl = "file://" + resolve(indexPath);
          const outDir = "assets";
          const outPath = join(outDir, "Laurin_Huebner_CV.pdf");
          if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

          const browser = await chromium.launch({
            args: ["--no-sandbox","--disable-setuid-sandbox","--allow-file-access-from-files","--disable-web-security"]
          });

          try {
            const ctx = await browser.newContext({ colorScheme: "light" });
            const page = await ctx.newPage();

            // Debug: Console/Netzwerk-Fehler mitschreiben
            page.on("console", m => console.log("[console]", m.type(), m.text()));
            page.on("pageerror", e => console.log("[pageerror]", e.message));
            page.on("requestfailed", r => console.log("[requestfailed]", r.url(), r.failure()?.errorText));

            await page.emulateMedia({ media: "print" });
            await page.addStyleTag({ content: `
              .actions, #themeToggle, #pdfAuto { display:none !important; }
              .qrbox img { display:none !important; }
            `});

            await page.goto(fileUrl, { waitUntil: "load", timeout: 60000 });

            await page.pdf({
              path: outPath,
              format: "A4",
              printBackground: true,
              margin: { top: "10mm", right: "10mm", bottom: "10mm", left: "10mm" }
            });

            if (!fs.existsSync(outPath) || fs.statSync(outPath).size < 10240) {
              throw new Error("PDF nicht erstellt oder zu klein");
            }
            console.log("✅ PDF OK:", outPath, fs.statSync(outPath).size, "bytes");
          } finally {
            await browser.close();
          }
          EOF

      - name: PDF erzeugen (Playwright)
        env:
          INDEX_PATH: ${{ env.INDEX_PATH }}
        run: |
          set -e
          node scripts/export-pdf.mjs
          echo "::group::assets"
          ls -la assets || true
          echo "::endgroup::"

      - name: Fallback installieren (wkhtmltopdf)
        if: ${{ failure() }}
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: PDF erzeugen (Fallback wkhtmltopdf)
        if: ${{ failure() }}
        env:
          INDEX_PATH: ${{ env.INDEX_PATH }}
        run: |
          mkdir -p assets
          IN="file://$(realpath "$INDEX_PATH")"
          OUT="assets/Laurin_Huebner_CV.pdf"
          echo "Fallback: wkhtmltopdf $IN → $OUT"
          wkhtmltopdf --enable-local-file-access "$IN" "$OUT"
          ls -la assets

      - name: Artifact hochladen (alle PDFs aus assets/)
        uses: actions/upload-artifact@v4
        with:
          name: Laurin_Huebner_CV
          path: assets/*.pdf
          if-no-files-found: error

      - name: Versuch: Direkt committen
        id: commit
        continue-on-error: true
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/*.pdf || true
          if git diff --cached --quiet; then
            echo "Kein Commit nötig (keine Änderungen)."
            exit 0
          fi
          git commit -m "chore(pdf): rebuild CV PDF"
          git push origin "${BRANCH}"

      - name: Fallback: Pull-Request erstellen
        if: steps.commit.outcome == 'failure'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(pdf): rebuild CV PDF"
          branch: pdf-update/${{ github.run_id }}
          title: "PDF aktualisieren"
          body: "Automatisch erzeugte PDF hinzugefügt/aktualisiert."
          add-paths: |
            assets/*.pdf
